client/src/components/loginButton/index.jsx

por ahora solo hice que vaya al home

feat(src/components/loginButton): create login button

---

client/src/redux/store/store.js

fix(src/redux/store): fix imports

---

API/index.ts
API/package.json

cambie la rama del main a deploy, agregue la variable port al conect, y la dependencia dotenv a package.json

feat(API/index.ts): added dotenv for deploy

---

client/src/components/PostForm/PostForm.jsx

Added form area for posting content on our web

feat(client/src/components/postForm): added form for posts

---

client/src/components/Home/Home.jsx
client/src/components/Home/ONGFilters.jsx
client/src/components/Home/PostFilters.jsx

refact(src/components/home): refact filters

---

API/src/routes/comments.ts
API/src/routes/index.ts
API/src/routes/posts.ts
API/src/routes/shelters.ts
API/src/routes/users.ts

Big refactor of all routes in backend. Detailed description of changes:
**Major refactor:**
- In posts.ts, there were 4 routes: one ordering by least liked, one ordering by most liked, one ordering by most recent, and other ordering for oldest. This was highly unpractical, so I kind of merged them into one very simple route. The most important thing about this is, allowing the code to be scalable, so if in the future we need to add an attribute to order by, we just need to add a word, and if we want to add a filter, we just need to add one line or two.
**Minor changes:**
- Unified all error messages (there used to be some in json, some in plain text, and formats were different all across files)
- Added a few comments (more in the future documentation of code)
- Beautified? and compacted …

refactor(API/src/routes/...): big refactor of files

---

API/prisma/schema.prisma
API/src/routes/users.ts

User detail was not sending correct array of followed shelters.

Fixed users.ts route.

---

API/src/routes/shelters.ts

fix(api/src/routes/shelters.ts): fixed put and post routes. did not have updated city and country attributes.

---

client/src/components/Landing/Carousel/Card.jsx
client/src/components/Landing/Carousel/index.jsx

conecte el componente carousel con el back :p

conecte el carousel con el back

---

API/prisma/schema.prisma
API/src/routes/posts.ts
API/src/routes/shelters.ts
API/src/routes/users.ts

fix(api/src/routes): fixed prisma model for posts belonging to a shelter. fixed routes.

---

client/src/components/OngForm/OngForm.jsx
client/src/components/OngForm/validationOngForm.js
client/src/components/UserForm/UserFom.jsx
client/src/components/UserForm/validationUserForm.js

fix(client/src/components/OngForm and client/src/components/UserForm): fix forms to create users and Ongs

fix(client/src/components/OngForm and client/src/components/UserForm): fix forms to create users and Ongs

---

client/src/components/Home/CardPost.jsx
client/src/components/Navbar/Navbar.jsx
client/src/redux/reducers/dataBack/managePosts/managePostsActions.js
client/src/redux/reducers/dataBack/managePosts/managePostsSlice.js

porfa acepten antes que se rompa de nuevo xd

fix conflicts: added functionality to likes, redirection to shelter creation form and fix shelter creation form

---

client/src/components/OngForm/OngForm.jsx
client/src/components/OngProfile/OngFormUpdate.jsx
client/src/components/OngProfile/OngProfile.jsx
client/src/components/OngProfile/UploadImage.jsx
client/src/index.js

Styled
Update ONG info tested
Create Post Works
validations Done

Ong Profile Updates

---

client/src/components/OngProfile/OngFormUpdate.jsx
client/src/components/OngProfile/UploadImage.jsx

Edit button on left side now controls reset (image) button too.

ONG profile minor fix

---

client/src/components/Landing/Navbar/index.jsx
client/src/components/Navbar/Navbar.jsx

NavBar icons now links to landing page

Navbar Links Updated

---

client/src/components/Home/Home.jsx
client/src/components/Home/ONGFilters.jsx
client/src/components/Home/Posts.jsx

Filter detail select box now displays its content the right way, after selecting the according filter group at the first select box. Also, its title or "display value", now shows a clearer text. 
Improved styling of the component, to make it more "visually stable".
Changed home page background color to match with Landing background color.

refactor(client/src/components/ONGFilters): improved detail select box.

---

client/src/components/Home/CardPost.jsx
client/src/components/Navbar/Navbar.jsx
client/src/components/PostDetail/Comments/Comment.jsx
client/src/redux/api/posts.js
client/src/redux/slices/manageUsers/actions.js
client/src/redux/slices/manageUsers/index.js

se queda guardado en el localStorage a que posts diste like y se puede editar comentarios

fix(src/components/home): fix likes and edit comment feature

---

API/src/routes/posts.ts
API/src/routes/shelters.ts
API/src/routes/users.ts

las rutas solo traen los enables y cree rutas que traen todo para el admin, fijense si les sirve y les convence, sino no lo mergeen

add functionality that brings only the enabling of the routes

---

API/src/routes/users.ts
client/src/App.js
client/src/components/AdminDashboard/AdminDashboard.jsx
client/src/components/Home/CardPost.jsx
client/src/components/Home/Posts.jsx
client/src/components/PostDetail/Comments/Comment.jsx
client/src/components/PostDetail/ModalEditPost.jsx
client/src/components/ProtectedRoute/index.jsx
client/src/redux/api/users.js

- Funcionalidad para convertir usuarios en admin
- ruta /admin protegida, solo podes entrar si estas logeado y si sos admin,
- icono de admin al lado del name en cardPost
- podes editar y eliminar cualquier post o comentario si sos admin

feat(src/components): convert admin functionality

---

client/src/components/Maps/MapView/MapView.jsx
client/src/components/OngProfile/OngProfile.jsx
client/src/components/OngProfile/Posts.jsx

Geolocalizacion 1.0.1

---

API/src/routes/users.ts
client/src/components/Home/SubscriptorsBar.jsx
client/src/components/UserProfile/UserProfile.jsx

el boton mostraba mas following de los que deberia
y un pequeño problema con la subBar

hotfix/button following  - userProfile

---

client/src/components/Page404/index.jsx

un poco de estilo para la pagina 404

styles(src/components/page404) un poco de estilo

---

API/src/routes/shelters.ts
client/src/components/Navbar/Navbar.jsx
client/src/components/Navbar/ProfilePanel.jsx
client/src/components/OngProfile/OngFormUpdate.jsx
client/src/components/OngProfile/OngProfile.jsx

- Cuando el usuario tiene shelter, en lugar de decir "Create Shelter" dira "Shelter settings"
- Los usuarios con shelter disabled no pueden crear post
- cuando entras a shelter settings aparece un sweet alert, diciendo que la shelter se encuentra disabled

las shelters disabled no pueden crear posts

---

client/src/components/Navbar/Navbar.jsx

la navbar se mostraba por encima del post detail

hotfix(client/src/components/navbar): z-49

---

client/src/components/UserProfile/ModalUserSheltersFollowed.jsx
client/src/components/UserProfile/UserProfile.jsx
client/src/components/UserProfile/UserProfileCardPost.jsx
client/src/components/UserProfile/UserSheltersFollowedCard.jsx
client/src/redux/api/shelters.js
client/tailwind.config.js

Now comes with follow and unfollow buttons when looking at the shelters other people follow, also now it has a responsive design.

User Profile

---

API/src/routes/goals.ts
API/src/routes/shelters.ts
client/src/components/Goals/BtnCreate.jsx
client/src/components/Goals/CardGoals.css
client/src/components/Goals/CardGoals.jsx
client/src/components/Goals/Goals.jsx
client/src/components/Goals/modalCreate/FormCreate.jsx
client/src/components/Goals/modalCreate/index.jsx
client/src/components/OngProfile/OngProfile.jsx
client/src/redux/api/goals.js

Backend: - added get, delete, and fixed enable/disable endpoints to goals route. 
Frontend: - added get, delete, enable, disable endpoints to goal.
- added delete button to goals
- fixed: now, when user create a goal, page update automatically and show the goal
- fixed: now, when use delete a goal, page update automatically and delete the goal
Still missing: - add buttons enable/disable goal (lo hago en el proximo pull request)
- show button create goal and delete/disable/enable only to shelter owner

feat(goals routes/goals endpoints/goals component): added delete/enable/disable

---

client/src/components/Goals/CardGoals.jsx

added buttons to enable disable goals. Now when a goal is disabled, user can't donate

feat(src/components/goals): added enable/disable goal

---

client/src/components/LearnMore/LearnMore.jsx
client/src/components/OngForm/OngForm.jsx
client/src/components/OngForm/UploadImage.jsx
client/src/components/OngProfile/ShelterStats.jsx

Now if you follow more than 3 shelters, the user is prompted to create an account or login to save the shelters followed

add responsive and dark mode in LearnMore and OngForm, and functionality with local storage of the following

---

client/src/components/Goals/Goals.jsx
client/src/components/OngProfile/Main/ProfileBottom.jsx

se rompia cuando no estabas logeado

hotfix ongProfile

---

API/src/routes/shelters.ts

ahora se mustran las fotos del author en trending

hotfix/ Carousel

---

client/src/components/Page404/index.jsx

darkmode page404

---

client/src/components/Home/Main/HomeNav.jsx

no se renderiza el boton, si no tenes shelter

fix btn create post

---

client/src/components/UserProfile/UserProfile.jsx
client/src/components/UserProfile/UserProfileCardPost.jsx

fix(client/src/components/userPrile): videos in cardpost

---

client/src/components/About/About.jsx
client/src/components/Landing/Footer/Footer.jsx
client/src/components/OngProfile/Main/ProfileFooter.jsx
client/src/components/OngProfile/Main/ProfileSidebar.jsx
client/src/components/OngProfile/Main/index.jsx

Fix: about us footer, added lightmode/darkmode and deleted donate button
Added: budget in shelter profile to show recollected money of a shelter
Fix: button darkmode with sidebar not expanded in ong profile
Fix: link to profile user in footer of shelter profile (now redirect to home if the user is logged out)

Branch lio
